### ISSUE TITLE
3.1.4 was modified as of 2021

### ISSUE THREAD

**Issue by MrKnight1234** [CODENAMEMystic/CodeHS-APCS-Java#10]
I noticed that they changed the problem for 3.1.4, I've included the current version. It is simple, just write in the method E. As mentioned before, please use this as an example and try to figure it out on your own. But if you want to be lazy, then no worries.  

=============Code_Below===============

public class PrintJava extends ConsoleProgram
{
    // You need to write 'printE()' method below
    public void run()
    {
        printK();
        System.out.println();
        printA();
        System.out.println();
        printR();
        System.out.println();
        printE();
        System.out.println();
        printL();
    }
    
    private void printK()
    {
        System.out.println("*   * ");
        System.out.println("* *   ");
        System.out.println("**    ");
        System.out.println("* *   ");
        System.out.println("*   * ");
    
    }
    
    private void printA()
    {
        System.out.println("*****");
        System.out.println("*   *");
        System.out.println("*****");
        System.out.println("*   *");
        System.out.println("*   *");
    }
    
    private void printR()
    {
        System.out.println("*****");
        System.out.println("*   *");
        System.out.println("****");
        System.out.println("*    *");
        System.out.println("*     *");
    }
    
    private void printE()
    {
        System.out.println("*****");
        System.out.println("*    ");
        System.out.println("*****");
        System.out.println("*    ");
        System.out.println("*****");
        
    }
    
    private void printL()
    {
        System.out.println("*    ");
        System.out.println("*    ");
        System.out.println("*    ");
        System.out.println("*    ");
        System.out.println("*****");   
        
    }
}

**Comment by CODENAMEMystic** [comment]
Thank you @MrKnight1234 !  I've updated 3.1.4 print java.java in the repo.

_Cred: MrKnight1234_
