### ISSUE TITLE
Unit 4 not working

### ISSUE THREAD

**Issue by blanjon009** [CODENAMEMystic/CodeHS-APCS-Java#11]
unit 4 code is all poorly written , it doesnt even come with the tester file.

**Comment by CODENAMEMystic** [comment]
I appreciate the feedback however do keep in mind this all was written 4 or so years ago. A lot has changed on CodeHS as i've came to find out from individuals reaching out to me. If you have anything to add to the repo please let me know ^_^

**Comment by tim44964** [comment]
Thank you I just have some problems and I am to stupid to figure it out.
Thanks tho for your help and I have others that I can't fix
